### ISSUE TITLE
Receiving one invitation for each channel and private conversation on bot (re)start

### ISSUE THREAD

**Issue by Coniface** [mautrix/slack#36]
Here is my backfill configuration:
```yaml
backfill:
        # Allow backfilling at all? Requires MSC2716 support on homeserver.
        enable: false
        # Maximum number of conversations to fetch from Slack when syncing team from Slack.
        # Must be 0-999
        conversations_count: 0
```
Yet, the first time the container started up, I had 80 invites from all the channels and private messages of my Slack.
I rejected them one by one to keep a clean UI in Element but each time the `mautrix-slack` container restarts, I get those same 80 invites again.

It is the only bridge that does that to me. Does anyone else experiences the same behaviour and knows how to fix it?

Like any other bridge, I'd expect to receive an invite only if a new message has been sent in one of the 80 channels.
