### ISSUE TITLE
Double Puppetting not working.

### ISSUE THREAD

**Issue by niebloomj** [mautrix/slack#53]
I believe I followed all the steps in the docs, and it is working for my other bridges, but it's not working for Slack. Here is what I have

> slack/config.yaml
```
# Settings for enabling double puppeting
double_puppet:
    # Servers to always allow double puppeting from.
    # This is only for other servers and should NOT contain the server the bridge is on.
    servers:
        anotherserver.example.org: https://matrix.anotherserver.example.org
    # Whether to allow client API URL discovery for other servers. When using this option,
    # users on other servers can use double puppeting even if their server URLs aren't
    # explicitly added to the servers map above.
    allow_discovery: false
    # Shared secrets for automatic double puppeting.
    # See https://docs.mau.fi/bridges/general/double-puppeting.html for instructions.
    secrets:
        matrix.frum.finance: "as_token:stringA"
```
> slack/registration.yaml
```
id: slack
url: http://localhost:29335
as_token: stringA
hs_token: stringB
sender_localpart: stringC
rate_limited: false
namespaces:
    users:
        - regex: ^@slack_bot:matrix\.frum\.finance$
          exclusive: true
        - regex: ^@slack_.*:matrix\.frum\.finance$
          exclusive: true
de.sorunome.msc2409.push_ephemeral: true
push_ephemeral: true
```
> dentrite/config.yaml
```
  config_files:
    - /home/admin/whatsapp/personal-registration.yaml
    - /home/admin/doublepuppet-registration.yaml
    - /home/admin/slack/registration.yaml
    - /home/admin/gmessages-registration.yaml
    - /home/admin/signal/registration.yaml
    - /home/admin/meta/instagram-registration.yaml
    - /home/admin/whatsapp/business-registration.yaml
    - /home/admin/discord/registration.yaml
```

Restart the bridge and then try to ping matrix:

![CleanShot 2024-07-22 at 15 13 02@2x](https://github.com/user-attachments/assets/2c21c22e-cc18-4024-8642-593051e2f528)
