### ISSUE TITLE
Slackbot renamed all the Slack rooms without the name

### ISSUE THREAD

**Issue by wapsi** [mautrix/slack#7]
I updated my bridge to the most recent version from git (2022-10-12 13:00 EET), and after I started the new bridge it immediately renamed all my Slack rooms to names without the original Slack room name:

![image](https://user-images.githubusercontent.com/11405096/195313462-6b1ae1cb-37a9-40a8-afbc-ad10a293d870.png)
My room naming configuration:

```
# Bridge config
bridge:
    # Localpart template of MXIDs for Slack users.
    # {{.}} is replaced with the internal ID of the Slack user.
    username_template: slack_{{.}}
    # Displayname template for Slack users.
    # TODO: document variables
    displayname_template: '{{.RealName}} (Slack)'
    bot_displayname_template: '{{.Name}} (Slack bot)'
    channel_name_template: 'Slack #{{.Name}}'
    portal_message_buffer: 128
```
It seems that the bridge is not able to update the #{{.Name}} to the real Slack room name anymore?
