### ISSUE TITLE
Display name templating is not functional

### ISSUE THREAD

**Issue by xangelix** [mautrix/slack#9]
My configuration, as far as I know, is correct to have matrix display names set to slack names, however they are the full slack user IDs instead.
E.g.

![image](https://user-images.githubusercontent.com/16216097/210654772-71382c17-65f8-4763-9404-25c6196b146f.png)

config.yml
```yml
appservice:
  address: http://matrix-mautrix-slack:8080
  as_token: <redacted>
  async_transactions: false
  bot:
    avatar: mxc://maunium.net/pVtzLmChZejGxLqmXtQjFxem
    displayname: Slack bridge bot
    username: slackbot
  database:
    max_conn_idle_time: null
    max_conn_lifetime: null
    max_idle_conns: 2
    max_open_conns: 20
    type: postgres
    uri: postgresql://matrix_mautrix_slack:<redacted>@matrix-postgres:5432/matrix_mautrix_slack?sslmode=disable
  ephemeral_events: true
  hostname: 0.0.0.0
  hs_token: <redacted>
  id: slack
  port: 8080
bridge:
  backfill:
    enable: false
    immediate_messages: 10
    incremental:
      max_messages:
        channel: -1
        dm: -1
        group_dm: -1
      messages_per_batch: 100
      post_batch_delay: 20
    unread_hours_threshold: 720
  bot_displayname_template: '{{.Name}} (bot)'
  channel_name_template: '#{{.Name}}'
  command_prefix: '!slack'
  delivery_receipts: true
  displayname_template: '{{.RealName}} (S)'
  double_puppet_allow_discovery: false
  double_puppet_server_map:
    <redacted>: http://matrix-nginx-proxy:12080
  encryption:
    allow: false
    allow_key_sharing: false
    appservice: false
    default: false
    require: false
    rotation:
      enable_custom: false
      messages: 100
      milliseconds: 604800000
    verification_levels:
      receive: unverified
      send: unverified
      share: cross-signed-tofu
  login_shared_secret_map:
    <redacted>: <redacted>
  management_room_text:
    additional_help: ''
    welcome: Hello, I'm a Slack bridge bot.
    welcome_connected: Use `help` for help.
    welcome_unconnected: Use `help` for help, or `login-token` or `login-password` to log in.
  message_error_notices: true
  message_handling_timeout:
    deadline: 60s
    error_after: 10s
  message_status_events: false
  permissions:
    <redacted>: user
  portal_message_buffer: 128
  provisioning:
    prefix: /_matrix/provision
    shared_secret: generate
  sync_direct_chat_list: false
  sync_with_custom_puppets: false
  username_template: slack_{{.}}
homeserver:
  address: http://matrix-nginx-proxy:12080
  async_media: false
  domain: <redacted>
  message_send_checkpoint_endpoint: null
  software: standard
  status_endpoint: null
logging:
  directory: ./logs
  file_date_format: '2006-01-02'
  file_json: false
  file_mode: 384
  file_name_format: ''
  print_json: false
  print_level: warn
  timestamp_format: Jan _2, 2006 15:04:05
```
registration.yml
```yml
as_token: <redacted>
de.sorunome.msc2409.push_ephemeral: true
hs_token: <redacted>
id: slack
namespaces:
  users:
  - exclusive: true
    regex: ^@slack_[a-z-A-Z0-9\-]+:<redacted>$
  - exclusive: true
    regex: ^@slackbot:<redacted>$
rate_limited: false
sender_localpart: _bot_slackbot
url: http://matrix-mautrix-slack:8080
```
